#!/usr/bin/env bash
# =============================================================================
# monitoring-server-setup-native.sh — server half of the Grafana + Prometheus +
# http-over-ssh monitoring stack, WITHOUT Docker.
#
# Everything runs as native systemd services on local packages. No containers,
# no Docker networks, no nginx-proxy container, no socat relay.
#
# Run this ON THE SERVER. It is idempotent: safe to re-run.
# It produces client-bundle.env, which the client script consumes.
#
# Usage:
#   sudo ./monitoring-server-setup-native.sh --dry-run        # show everything, change nothing
#   sudo ./monitoring-server-setup-native.sh                  # do it (prompts before writing)
#   sudo ./monitoring-server-setup-native.sh --yes
#   sudo ./monitoring-server-setup-native.sh --add-client-key "ssh-ed25519 AAAA... dev"
#   sudo ./monitoring-server-setup-native.sh --rollback
#
# Layout it creates (all under /etc and /var/lib, distro-standard):
#   /etc/http-over-ssh/            proxy key + known_hosts  (mode 700)
#   /etc/prometheus/prometheus.yml scrape config
#   /etc/prometheus/rules/*.yml    alert rules
#   /etc/grafana/provisioning/     datasource
#   /etc/nginx/sites-available/monitoring-grafana.conf
#   systemd units: http-over-ssh, prometheus, grafana-server, node_exporter
#
# Ports: 8080 proxy (loopback), 9090 prometheus (loopback),
#        9100 node_exporter, 3000 grafana (loopback), 2201-2203 tunnels.
# Nothing except nginx 80/443 is public.
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------- defaults ---
DOMAIN="${DOMAIN:-monitoring.example.com}"
GRAFANA_HOST="${GRAFANA_HOST:-grafana}"
TUNNEL_HOST="${TUNNEL_HOST:-127.0.0.1}"     # where reverse tunnels are bound
TUNNEL_PORTS=(2201 2202 2203)
PROXY_PORT="${PROXY_PORT:-8080}"
PROM_PORT="${PROM_PORT:-9090}"
GRAFANA_PORT="${GRAFANA_PORT:-3000}"
EXPORT_PORT="${EXPORT_PORT:-9100}"
ADMIN_PORT="${ADMIN_PORT:-8099}"
RETENTION_TIME="${RETENTION_TIME:-90d}"
RETENTION_SIZE="${RETENTION_SIZE:-20GB}"
CONF_DIR="${CONF_DIR:-/etc/http-over-ssh}"
STATE_DIR="${STATE_DIR:-/var/lib/monitoring}"
SSHD_DROPIN="56-monitor-tunnel.conf"
PROXY_VERSION="${PROXY_VERSION:-0.3.7}"
BUNDLE="${BUNDLE:-/etc/http-over-ssh/client-bundle.env}"

DRY_RUN=0
ASSUME_YES=0
ROLLBACK=0
CLIENT_KEY=""
SUDO=""
# WEB_MODE:
#   nginx  - publish Grafana through nginx on your domain (HTTPS if a cert exists)
#   none   - no web server; Grafana stays on 127.0.0.1, reach it with an SSH
#            tunnel. Nothing is exposed at all.
WEB_MODE="${WEB_MODE:-nginx}"

c_ok()   { printf '\033[0;32m  ok\033[0m   %s\n' "$*"; }
c_warn() { printf '\033[0;33m  warn\033[0m %s\n' "$*"; }
c_err()  { printf '\033[0;31m  fail\033[0m %s\n' "$*" >&2; }
c_step() { printf '\n\033[1;36m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
c_note() { printf '       %s\n' "$*"; }
die()    { c_err "$*"; exit 1; }
have()   { command -v "$1" >/dev/null 2>&1; }

sh_run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    printf '       [dry-run] %s\n' "$1"
  else
    bash -c "$1"
  fi
}

confirm() {
  [ "$ASSUME_YES" -eq 1 ] && return 0
  [ "$DRY_RUN" -eq 1 ] && return 0
  local r
  read -r -p "  proceed? [y/N] " r
  case "$r" in [yY]*) return 0 ;; *) die "aborted by operator" ;; esac
}

usage() {
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)        DRY_RUN=1 ;;
    --yes|-y)         ASSUME_YES=1 ;;
    --rollback)       ROLLBACK=1 ;;
    --domain)         DOMAIN="$2"; shift ;;
    --grafana-host)   GRAFANA_HOST="$2"; shift ;;
    --tunnel-host)    TUNNEL_HOST="$2"; shift ;;
    --add-client-key) CLIENT_KEY="$2"; shift ;;
    --web)            WEB_MODE="$2"; shift ;;
    --help|-h)        usage ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
  shift
done

[ "$(id -u)" -eq 0 ] && SUDO="" || { have sudo || die "sudo not found"; SUDO="sudo"; }

# Validate --web up front. Placing this inside the `none` branch would make it
# unreachable for every other value, so a typo silently fell through to nginx.
case "$WEB_MODE" in
  nginx|none) ;;
  *) die "--web must be 'nginx' or 'none' (got '$WEB_MODE')" ;;
esac

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

write_native_bundle() {
  c_step "Client bundle"
  VPS_IP="$(ip -4 -br addr show scope global 2>/dev/null | awk '{print $3}' | cut -d/ -f1 | head -1)"
  [ -z "$VPS_IP" ] && VPS_IP="<set-your-server-ip>"
  HOST_FPR="$(ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub 2>/dev/null | awk '{print $2}')"
  PROXY_PUB=""
  [ -f "$CONF_DIR/id_ed25519.pub" ] && PROXY_PUB="$(cat "$CONF_DIR/id_ed25519.pub")"
  GF_PW=""
  [ -f "$STATE_DIR/grafana-admin-password" ] && GF_PW="$(cat "$STATE_DIR/grafana-admin-password")"

  if [ "$DRY_RUN" -eq 0 ]; then
    umask 077
    cat > "$BUNDLE" <<EOF
# Generated by monitoring-server-setup-native.sh. Mode 600 — contains a password.
#   scp <server>:$BUNDLE <client>:
#   ./monitoring-client-setup.sh --bundle client-bundle.env
VPS_HOST=$VPS_IP
VPS_HOST_KEY_FINGERPRINT=$HOST_FPR
TUNNEL_PORT=${TUNNEL_PORTS[0]}
PROXY_PUBKEY=$PROXY_PUB
GRAFANA_URL=$1
GRAFANA_USER=admin
GRAFANA_PASSWORD=$GF_PW
EOF
    chmod 600 "$BUNDLE"
    c_ok "written: $BUNDLE"
  else
    c_note "[dry-run] would write $BUNDLE"
  fi
}

native_summary() {
cat <<EOF

$(printf '\033[1;32m')=========================================================
 Native server setup complete — no Docker involved.
=========================================================$(printf '\033[0m')

 Grafana: $1
   admin / password in $STATE_DIR/grafana-admin-password

 Next, on each client machine:

   scp $BUNDLE ./monitoring-client-setup.sh <client>:
   chmod +x monitoring-client-setup.sh
   ./monitoring-client-setup.sh --bundle client-bundle.env --dry-run
   ./monitoring-client-setup.sh --bundle client-bundle.env --name my-laptop

 Then back here:

   ./monitoring-server-setup-native.sh --add-client-key "ssh-ed25519 AAAA... my-laptop"

 Verify:
   systemctl status http-over-ssh prometheus grafana-server
   curl -s http://127.0.0.1:$PROM_PORT/api/v1/query?query=up

EOF
}


# =================================================== distro / package layer ==
detect_distro() {
  if   [ -r /etc/os-release ]; then . /etc/os-release; echo "${ID:-unknown}"
  else echo unknown; fi
}
DISTRO="$(detect_distro)"
case "$DISTRO" in
  debian|ubuntu) PKGS="apt-get"; PKG_N="prometheus prometheus-node-exporter" ;;
  fedora|rhel|centos|rocky|alma) PKGS="dnf"; PKG_N="prometheus node_exporter" ;;
  arch)           PKGS="pacman"; PKG_N="prometheus prometheus-node-exporter" ;;
  alpine)         PKGS="apk";  PKG_N="prometheus node_exporter" ;;
  opensuse*)      PKGS="zypper"; PKG_N="prometheus prometheus-node_exporter" ;;
  *) c_warn "unrecognised distro '$DISTRO' — assuming apt-get"; PKGS="apt-get"
     PKG_N="prometheus prometheus-node-exporter" ;;
esac

install_pkgs() {
  case "$PKGS" in
    apt-get) $SUDO apt-get update -qq
             $SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y $PKG_N curl ca-certificates ;;
    dnf)     $SUDO dnf install -y $PKG_N curl ca-certificates ;;
    pacman)  $SUDO pacman -S --needed --noconfirm $PKG_N curl ca-certificates ;;
    apk)     $SUDO apk add --no-cache $PKG_N curl ca-certificates ;;
    zypper)  $SUDO zypper --non-interactive install $PKG_N curl ca-certificates ;;
  esac
}

# Grafana is not in most distro repos; add the official one.
install_grafana() {
  if have grafana-server || systemctl list-unit-files 2>/dev/null | grep -q '^grafana-server'; then
    c_ok "grafana already installed"
    return 0
  fi
  c_step "Grafana (official apt repo)"
  case "$PKGS" in
    apt-get)
      # Repo line verified live: serves Grafana 13.x for amd64/arm64.
      # Signing key fingerprint B53AE77BADB630A683046005963FA27710458545.
      sh_run "mkdir -p /etc/apt/keyrings"
      sh_run "curl -fsSL https://apt.grafana.com/gpg.key | gpg --dearmor -o /etc/apt/keyrings/grafana.gpg"
      sh_run "chmod 644 /etc/apt/keyrings/grafana.gpg"
      sh_run "printf 'deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main\n' > /etc/apt/sources.list.d/grafana.list"
      sh_run "apt-get update -qq"
      sh_run "DEBIAN_FRONTEND=noninteractive apt-get install -y grafana"
      ;;
    dnf)     sh_run "$SUDO dnf install -y https://dl.grafana.com/oss/rpm/grafana-enterprise-$(rpm -E %_arch).rpm" ;;
    pacman)  c_warn "install Grafana from https://grafana.com/docs/grafana/latest/setup-grafana/installation/ (not Arch official)"
             return 0 ;;
    *)       c_warn "install Grafana manually for '$DISTRO' — see https://grafana.com/docs/grafana/latest/setup-grafana/installation/" ;;
  esac
}

# ============================================================== add-client-key ==
add_client_key() {
  [ -n "$CLIENT_KEY" ] || die "--add-client-key needs a public key"
  case "$CLIENT_KEY" in
    ssh-ed25519\ *|ssh-rsa\ *|ecdsa-sha2-*\ *) ;;
    *) die "that does not look like an SSH public key" ;;
  esac

  local port="${TUNNEL_PORTS[0]}"
  local comment; comment="$(printf '%s' "$CLIENT_KEY" | awk '{print $NF}')"
  local line="restrict,port-forwarding,permitlisten=\"${TUNNEL_HOST}:${port}\" ${CLIENT_KEY}"

  c_step "Authorizing client tunnel key on ${TUNNEL_HOST}:${port}"
  sh_run "install -d -m 700 -o monitor -g monitor /home/monitor/.ssh"
  sh_run "touch /home/monitor/.ssh/authorized_keys; chown monitor:monitor /home/monitor/.ssh/authorized_keys; chmod 600 /home/monitor/.ssh/authorized_keys"

  # Merge with awk, and verify we did not drop another device's line. The read
  # must be privileged: the file is 600 and owned by monitor, so an unprivileged
  # read silently returns nothing and we would clobber the other devices.
  local tmp before=0 after
  tmp="$(mktemp)"
  if [ -s /home/monitor/.ssh/authorized_keys ]; then
    before="$(grep -cve '^[[:space:]]*$' /home/monitor/.ssh/authorized_keys || true)"
    awk -v c="$comment" 'index($0, c) == 0' /home/monitor/.ssh/authorized_keys > "$tmp"
  else
    : > "$tmp"
  fi
  printf '%s\n' "$line" >> "$tmp"
  after="$(grep -cve '^[[:space:]]*$' "$tmp" || true)"
  if [ "$before" -gt 0 ] && [ "$after" -lt "$before" ]; then
    die "merge would drop entries (had $before, produced $after) — refusing"
  fi
  echo "  --- resulting authorized_keys ($after line(s), was $before) ---"
  sed 's/^/       /' "$tmp"
  confirm
  if [ "$DRY_RUN" -eq 0 ]; then
    install -m 600 -o monitor -g monitor "$tmp" /home/monitor/.ssh/authorized_keys
    rm -f "$tmp"
    c_ok "installed: $(ssh-keygen -lf /home/monitor/.ssh/authorized_keys | tail -1)"
  else
    rm -f "$tmp"
  fi

  c_step "Waiting for the client tunnel on ${TUNNEL_HOST}:${port}"
  if [ "$DRY_RUN" -eq 1 ]; then c_note "[dry-run] would poll and pin host keys"; return 0; fi
  local ok=0
  for i in $(seq 1 30); do
    if nc -z -w 2 "$TUNNEL_HOST" "$port" 2>/dev/null; then ok=1; break; fi
    printf '       waiting... (%ds/150s) — start the client tunnel\n' "$((i*5))"
    sleep 5
  done
  [ "$ok" -eq 1 ] || { c_err "no tunnel after 150s"; return 1; }
  c_ok "tunnel is listening"

  c_step "Pinning client host key(s)"
  # ALL key types: knownhosts rejects any unlisted type for a known host.
  local scan; scan="$(mktemp)"
  ssh-keyscan -p "$port" "$TUNNEL_HOST" 2>/dev/null | grep -v '^#' > "$scan" || true
  [ -s "$scan" ] || { c_err "ssh-keyscan returned nothing"; rm -f "$scan"; return 1; }
  c_ok "$(wc -l < "$scan") host key type(s) offered:"
  ssh-keygen -lf "$scan" | sed 's/^/       /'
  echo
  echo "  Verify on the CLIENT:  ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub"
  echo
  confirm

  local kh="$CONF_DIR/known_hosts"
  mkdir -p "$CONF_DIR"; touch "$kh"
  { grep -v "^\[${TUNNEL_HOST}\]:${port}[[:space:]]" "$kh" 2>/dev/null || true; cat "$scan"; } > "$kh.new"
  install -m 600 "$kh.new" "$kh"; rm -f "$kh.new" "$scan"
  c_ok "known_hosts updated:"; ssh-keygen -lf "$kh" | sed 's/^/       /'

  c_step "Restarting the proxy"
  systemctl restart http-over-ssh
  sleep 2
  journalctl -u http-over-ssh -n 6 --no-pager 2>&1 | sed 's/^/       /'
  c_note "look for: SSH connection to promssh@ established"
}

# ================================================================== rollback ==
rollback() {
  c_step "Rollback"
  echo "  This removes the monitoring units, configs, user and firewall rules."
  echo "  Prometheus/Grafana data in $STATE_DIR is KEPT."
  echo "  Backups: $STATE_DIR/backups-*"
  confirm
  for u in http-over-ssh grafana-server prometheus; do
    systemctl disable --now "$u" 2>/dev/null || true
    rm -f "/etc/systemd/system/$u.service"
  done
  systemctl daemon-reload
  c_ok "units removed"

  rm -f /etc/ssh/sshd_config.d/"$SSHD_DROPIN"
  $SUDO sshd -t 2>/dev/null && systemctl reload ssh 2>/dev/null && c_ok "sshd restored"

  # Remove UFW rules by comment text, not by index (indices shift).
  if have ufw; then
    while ufw status numbered 2>/dev/null | grep -q 'monitoring tunnel\|monitoring node_exporter'; do
      local n
      n="$(ufw status numbered | grep 'monitoring tunnel\|monitoring node_exporter' | head -1 | awk -F']' '{print $1}' | tr -d '[')"
      echo y | ufw delete "$n" || break
    done
    c_ok "ufw rules removed"
  fi

  rm -f /etc/nginx/sites-enabled/"$GRAFANA_HOST.conf"
  rm -f /etc/nginx/sites-available/"$GRAFANA_HOST.conf"
  if have nginx && have systemctl; then
    nginx -t >/dev/null 2>&1 && systemctl reload nginx && c_ok "nginx vhost removed"
  fi

  userdel -r monitor 2>/dev/null && c_ok "user monitor removed" || true
  echo
  c_ok "rollback complete. Data kept in $STATE_DIR (delete it by hand to purge)."
}

[ "$ROLLBACK" -eq 1 ] && { rollback; exit 0; }
[ -n "$CLIENT_KEY" ] && { add_client_key; exit 0; }

# ================================================================ preflight ===
c_step "Preflight ($DISTRO)"
have systemctl || die "systemd is required — this script has no SysV fallback"
c_ok "systemd present"
have curl || c_warn "curl missing; needed to fetch http-over-ssh"
have ssh-keyscan || die "ssh-keyscan missing (install openssh-client)"

# Port conflicts are the most common reason a native install fails late.
c_step "Port availability"
for p in "$PROXY_PORT" "$PROM_PORT" "$GRAFANA_PORT" "$EXPORT_PORT" "${TUNNEL_PORTS[@]}"; do
  if ss -lnt 2>/dev/null | awk '{print $4}' | grep -qE "(^|:)$p\$"; then
    owner="$(ss -lntp 2>/dev/null | awk -v P=":$p\$" '$4 ~ P {print $NF}' | head -1)"
    # Grafana/prometheus may already be installed and running — that is fine.
    case "$p" in
      "$GRAFANA_PORT"|"$PROM_PORT"|"$EXPORT_PORT")
        if have systemctl && systemctl is-active --quiet "grafana-server" 2>/dev/null && [ "$p" = "$GRAFANA_PORT" ]; then
          c_ok "port $p already in use by grafana-server (expected on re-run)"
        elif have systemctl && systemctl is-active --quiet prometheus 2>/dev/null && [ "$p" = "$PROM_PORT" ]; then
          c_ok "port $p already in use by prometheus (expected on re-run)"
        elif have systemctl && systemctl is-active --quiet prometheus-node-exporter 2>/dev/null && [ "$p" = "$EXPORT_PORT" ]; then
          c_ok "port $p already in use by node_exporter (expected on re-run)"
        else
          c_warn "port $p in use: $owner"
        fi ;;
      "${TUNNEL_PORTS[0]}")
        c_ok "port $p in use — a client tunnel is up (expected)" ;;
      *)
        c_warn "port $p already in use: $owner" ;;
    esac
  else
    c_ok "port $p free"
  fi
done

# ============================================================== packages =====
c_step "Packages"
if [ "$DRY_RUN" -eq 1 ]; then
  sh_run "$PKGS install $PKG_N"
else
  install_pkgs
  c_ok "prometheus + node_exporter present"
fi
install_grafana

# =============================================================== backups ====
c_step "Backup"
BD="$STATE_DIR/backups-$(date +%F-%H%M%S)"
sh_run "mkdir -p '$BD'"
sh_run "cp -a /etc/ssh/sshd_config.d '$BD/sshd_config.d' 2>/dev/null || true"
sh_run "cp -a /etc/prometheus '$BD/prometheus' 2>/dev/null || true"
sh_run "cp -a /etc/grafana/provisioning '$BD/grafana-provisioning' 2>/dev/null || true"
sh_run "cp -a '$CONF_DIR' '$BD/http-over-ssh' 2>/dev/null || true"
sh_run "ufw status numbered > '$BD/ufw-before.txt' 2>/dev/null || true"
c_ok "backup dir: $BD"

# ========================================================== tunnel user ======
c_step "Restricted tunnel user 'monitor'"
if getent passwd monitor >/dev/null; then
  c_ok "already exists"
else
  sh_run "useradd -m -s /usr/sbin/nologin -c 'Monitoring reverse tunnels' monitor"
fi
sh_run "usermod -p '*' monitor"
sh_run "install -d -m 700 -o monitor -g monitor /home/monitor/.ssh"
sh_run "touch /home/monitor/.ssh/authorized_keys"
sh_run "chown monitor:monitor /home/monitor/.ssh/authorized_keys"
sh_run "chmod 600 /home/monitor/.ssh/authorized_keys"
c_ok "monitor: nologin, locked password, key-only"

# ================================================================ sshd =======
c_step "sshd drop-in $SSHD_DROPIN"
# Individual ports, never a range: UFW's multiport extension can be absent and
# then a range rule is accepted but never reaches the kernel.
PERMIT=""
for p in "${TUNNEL_PORTS[@]}"; do PERMIT+=" ${TUNNEL_HOST}:$p"; done
cat > "$STAGE/$SSHD_DROPIN" <<EOF
Match User monitor
    AllowTcpForwarding remote
    GatewayPorts clientspecified
    PermitListen$PERMIT
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    PermitTunnel no
    ClientAliveInterval 15
    ClientAliveCountMax 3
    ForceCommand /usr/sbin/nologin
EOF
echo "  --- proposed drop-in ---"; sed 's/^/       /' "$STAGE/$SSHD_DROPIN"
confirm
sh_run "install -m 644 '$STAGE/$SSHD_DROPIN' /etc/ssh/sshd_config.d/$SSHD_DROPIN"
if [ "$DRY_RUN" -eq 0 ]; then
  sshd -t || die "sshd config INVALID — not reloading"
  c_ok "sshd -t passed"
  systemctl reload ssh
  c_ok "sshd reloaded; effective:"
  sshd -T -C user=monitor,host=x,addr=1.2.3.4 \
    | grep -Ei '^(allowtcpforwarding|gatewayports|permitlisten|forcecommand|clientaliveinterval) ' | sed 's/^/       /'
fi

# ============================================================== firewall ====
c_step "Firewall (only if ufw is present)"
if have ufw; then
  for p in "${TUNNEL_PORTS[@]}"; do
    sh_run "ufw allow from 127.0.0.1 to any port $p proto tcp comment 'monitoring tunnel $p'"
    sh_run "ufw allow from ::1 to any port $p proto tcp comment 'monitoring tunnel $p v6'"
  done
  if [ "$DRY_RUN" -eq 0 ]; then
    missing=0
    for p in "${TUNNEL_PORTS[@]}"; do
      ufw status | grep -q "port $p proto tcp.*ALLOW" || { c_err "UFW lacks port $p"; missing=1; }
    done
    [ "$missing" -eq 0 ] && c_ok "ufw verified" || c_warn "review: ufw status numbered"
  fi
else
  c_warn "ufw not installed — skipping firewall (tunnels bind to loopback by default)"
fi

# ======================================================= http-over-ssh =======
c_step "http-over-ssh $PROXY_VERSION (prebuilt release binary)"
sh_run "install -d -m 700 '$CONF_DIR'"
sh_run "install -d -m 755 '$STATE_DIR'"

if [ -x /usr/local/bin/http-over-ssh ]; then
  c_ok "already installed"
else
  ARCH="$(uname -m)"
  case "$ARCH" in
    x86_64|amd64) ASSET_ARCH="amd64" ;;
    aarch64|arm64) ASSET_ARCH="arm64" ;;
    *) c_warn "no prebuilt binary for '$ARCH'; falling back to `go install`"
       sh_run "GOBIN=/usr/local/bin go install github.com/digineo/http-over-ssh@v${PROXY_VERSION}"
       ASSET_ARCH="" ;;
  esac
  if [ -n "$ASSET_ARCH" ]; then
    URL="https://github.com/digineo/http-over-ssh/releases/download/v${PROXY_VERSION}/http-over-ssh_${PROXY_VERSION}_linux_${ASSET_ARCH}.tar.gz"
    c_note "fetching $URL"
    sh_run "curl -fsSL -o '$STAGE/hos.tgz' '$URL'"
    # Verify the published checksum when we can fetch it.
    sh_run "curl -fsSL -o '$STAGE/checksums.txt' 'https://github.com/digineo/http-over-ssh/releases/download/v${PROXY_VERSION}/checksums.txt' || true"
    if [ "$DRY_RUN" -eq 0 ] && [ -f "$STAGE/checksums.txt" ]; then
      want="$(grep "linux_${ASSET_ARCH}.tar.gz" "$STAGE/checksums.txt" | awk '{print $1}')"
      got="$(sha256sum "$STAGE/hos.tgz" | awk '{print $1}')"
      [ -n "$want" ] && [ "$want" = "$got" ] && c_ok "checksum verified" \
        || c_warn "checksum mismatch or unavailable — review before trusting this binary"
    fi
    sh_run "tar -xzf '$STAGE/hos.tgz' -C '$STAGE' http-over-ssh"
    sh_run "install -m 755 '$STAGE/http-over-ssh' /usr/local/bin/http-over-ssh"
    c_ok "installed /usr/local/bin/http-over-ssh"
  fi
fi

if [ "$DRY_RUN" -eq 0 ]; then
  c_note "version: $(/usr/local/bin/http-over-ssh -help 2>&1 | head -1)"
fi

# Proxy key
if [ -f "$CONF_DIR/id_ed25519" ]; then
  c_ok "proxy key already exists (reused)"
else
  sh_run "ssh-keygen -t ed25519 -N '' -C 'http-over-ssh@$(hostname -s)' -f '$CONF_DIR/id_ed25519' -q"
  sh_run "chmod 600 '$CONF_DIR/id_ed25519'; chmod 644 '$CONF_DIR/id_ed25519.pub'"
  c_ok "proxy key generated"
fi

# known_hosts MUST exist — the proxy log.Fatal()s without it.
# Write into the stage dir and install it, so --dry-run never touches /etc.
if [ ! -s "$CONF_DIR/known_hosts" ]; then
  cat > "$STAGE/known_hosts" <<EOF
# http-over-ssh host key pinning. The proxy refuses to start without this file
# and rejects any unlisted key type for a host it already knows, so pin every
# type the device offers:
#   ssh-keyscan -p ${TUNNEL_PORTS[0]} ${TUNNEL_HOST} 2>/dev/null | grep -v '^#' >> $CONF_DIR/known_hosts
EOF
  sh_run "install -m 600 '$STAGE/known_hosts' '$CONF_DIR/known_hosts'"
  c_ok "known_hosts placeholder created"
else
  c_ok "known_hosts already present"
fi

# ======================================================== systemd units ======
c_step "systemd units"

cat > "$STAGE/http-over-ssh.service" <<EOF
[Unit]
Description=http-over-ssh metrics proxy (SSH over HTTP)
Documentation=https://github.com/digineo/http-over-ssh
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# The binary reads keys AND known_hosts from \$HOS_KEY_DIR and exits if
# known_hosts is missing. There is no key-file flag.
Environment=HOS_KEY_DIR=$CONF_DIR
Environment=HOS_LISTEN=127.0.0.1:$PROXY_PORT
ExecStart=/usr/local/bin/http-over-ssh -listen 127.0.0.1:$PROXY_PORT
Restart=always
RestartSec=10
User=root
# It only needs its own key dir and the network.
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
NoNewPrivileges=yes
ReadWritePaths=$STATE_DIR
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX

[Install]
WantedBy=multi-user.target
EOF

cat > "$STAGE/prometheus.service" <<EOF
[Unit]
Description=Prometheus (native)
Documentation=https://prometheus.io
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecStart=/usr/bin/prometheus \\
  --config.file=/etc/prometheus/prometheus.yml \\
  --storage.tsdb.path=$STATE_DIR/prometheus \\
  --storage.tsdb.retention.time=$RETENTION_TIME \\
  --storage.tsdb.retention.size=$RETENTION_SIZE \\
  --web.listen-address=127.0.0.1:$PROM_PORT \\
  --web.enable-lifecycle
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=10
StateDirectory=prometheus

[Install]
WantedBy=multi-user.target
EOF

cat > "$STAGE/grafana-server.service.override" <<'EOF'
# Grafana ships its own unit; we only override the listen address and flags.
[Service]
ExecStart=
ExecStart=/usr/sbin/grafana-server \\
  --config=/etc/grafana/grafana.ini \\
  --packaging=docker cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana \\
  cfg:default.server.http_port=3000 \\
  cfg:default.server.http_addr=127.0.0.1 \\
  cfg:default.server.root_url=https://DOMAIN_PLACEHOLDER/
EOF

echo "  --- units to install ---"
for f in http-over-ssh.service prometheus.service grafana-server.service.override; do
  echo "    $f"
done
confirm
sh_run "install -m 644 '$STAGE/http-over-ssh.service' /etc/systemd/system/http-over-ssh.service"
sh_run "install -m 644 '$STAGE/prometheus.service' /etc/systemd/system/prometheus.service"

# ========================================================== node_exporter ====
c_step "node_exporter for the server itself"
if systemctl list-unit-files 2>/dev/null | grep -q 'prometheus-node-exporter'; then
  sh_run "mkdir -p /etc/systemd/system/prometheus-node-exporter.service.d"
  cat > "$STAGE/ne-override.conf" <<EOF
[Service]
ExecStart=
ExecStart=/usr/bin/prometheus-node-exporter --web.listen-address=127.0.0.1:$EXPORT_PORT
EOF
  sh_run "install -m 644 '$STAGE/ne-override.conf' /etc/systemd/system/prometheus-node-exporter.service.d/override.conf"
  sh_run "systemctl daemon-reload"
  sh_run "systemctl enable --now prometheus-node-exporter"
  sh_run "systemctl restart prometheus-node-exporter"
  c_ok "node_exporter on 127.0.0.1:$EXPORT_PORT"
else
  c_warn "no prometheus-node-exporter unit — install it, or remove the node-local job"
fi

# ========================================================== prometheus.yml ===
c_step "Prometheus config"
mkdir -p "$STAGE/prom/rules" "$STAGE/grafana/provisioning/datasources"
DEVICES=()
[ -f "$STATE_DIR/devices.list" ] && mapfile -t DEVICES < "$STATE_DIR/devices.list"

{
cat <<'EOF'
global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: http-over-ssh
    static_configs:
      - targets: ['127.0.0.1:8080']

  # Remote devices reached through the SSH proxy.
  # Target = the device's SSH endpoint, not the exporter.
  - job_name: node-ssh
    proxy_url: http://127.0.0.1:8080/
    metrics_path: /localhost:9100/metrics
    basic_auth:
      username: promssh
      password: unused
    relabel_configs:
      - source_labels: [device]
        target_label: instance
    static_configs:
EOF
if [ ${#DEVICES[@]} -eq 0 ]; then
  printf "      - targets: ['%s:%s']\n        labels:\n          device: REPLACE_ME\n" "$TUNNEL_HOST" "${TUNNEL_PORTS[0]}"
else
  for d in "${DEVICES[@]}"; do
    [ -z "$d" ] && continue
    printf "      - targets: ['%s:%s']\n        labels:\n          device: %s\n" "$TUNNEL_HOST" "${d##*:}" "${d%%:*}"
  done
fi
cat <<'EOF'

  # The server itself.
  - job_name: node-local
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          device: THISHOST
    relabel_configs:
      - source_labels: [device]
        target_label: instance
EOF
} | sed -e "s|THISHOST|$(hostname -s)|g" -e "s|127.0.0.1:${PROM_PORT}|127.0.0.1:${PROM_PORT}|g" \
  > "$STAGE/prom/prometheus.yml"

cat > "$STAGE/prom/rules/node.yml" <<'EOF'
groups:
  - name: node
    rules:
      - alert: DeviceDown
        expr: up{job="node-ssh"} == 0
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "{{ $labels.instance }} has not been scraped for 10 minutes"

      - alert: ProxyDown
        expr: up{job="http-over-ssh"} == 0
        for: 2m
        labels: { severity: critical }
        annotations:
          summary: "http-over-ssh proxy is down"

      - alert: HighMemory
        expr: 1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > 0.90
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "{{ $labels.instance }} memory above 90%"

      # vfat excluded: /boot/efi is a small EFI partition that always reports
      # ~100% full and would otherwise fire on every scrape.
      - alert: LowDisk
        expr: node_filesystem_avail_bytes{fstype!~"tmpfs|overlay|squashfs|ramfs|vfat"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay|squashfs|ramfs|vfat"} < 0.10
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "{{ $labels.instance }} {{ $labels.mountpoint }} has under 10% free"

      - alert: HighCPU
        expr: 1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) > 0.90
        for: 15m
        labels: { severity: warning }
        annotations:
          summary: "{{ $labels.instance }} CPU above 90% for 15 minutes"
EOF

cat > "$STAGE/grafana/provisioning/datasources/prometheus.yml" <<'EOF'
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 30s
EOF

echo "  --- prometheus.yml scrape jobs ---"
grep -E 'job_name|targets:' "$STAGE/prom/prometheus.yml" | sed 's/^/       /'
confirm

sh_run "install -d -m 755 /etc/prometheus/rules"
sh_run "install -m 644 '$STAGE/prom/prometheus.yml' /etc/prometheus/prometheus.yml"
sh_run "install -m 644 '$STAGE/prom/rules/node.yml' /etc/prometheus/rules/node.yml"
sh_run "install -d -m 755 /etc/grafana/provisioning/datasources"
sh_run "install -m 644 '$STAGE/grafana/provisioning/datasources/prometheus.yml' /etc/grafana/provisioning/datasources/prometheus.yml"

# ============================================================== validate =====
c_step "Validate BEFORE starting"
if [ "$DRY_RUN" -eq 0 ]; then
  if have promtool; then
    promtool check config /etc/prometheus/prometheus.yml && c_ok "promtool: config valid"
  else
    c_warn "promtool not found; skipping config validation"
  fi
  if have nginx; then
    nginx -t >/dev/null 2>&1 && c_ok "nginx config valid" || c_warn "nginx -t reported a problem"
  fi
fi

# ============================================================== grafana ======
c_step "Grafana settings"
sh_run "mkdir -p $STATE_DIR/grafana /var/log/grafana /etc/grafana/provisioning/datasources"
if [ "$DRY_RUN" -eq 0 ]; then
  GF_PW="$(openssl rand -base64 24 2>/dev/null | tr -d '\n' || head -c 24 /dev/urandom | base64 | tr -d '\n')"
  # Use the grafana CLI so the password is hashed properly rather than stored raw.
  if have grafana-cli; then
    grafana-cli --homepath /usr/share/grafana admin reset-admin-password "$GF_PW" \
      --config /etc/grafana/grafana.ini >/dev/null 2>&1 || true
  fi
  printf '%s' "$GF_PW" > "$STATE_DIR/grafana-admin-password"
  chmod 600 "$STATE_DIR/grafana-admin-password"
  c_ok "admin password written to $STATE_DIR/grafana-admin-password (mode 600)"
fi

# Grafana must not bind publicly; nginx fronts it.
sh_run "sed -i 's/^;http_addr =.*/http_addr = 127.0.0.1/; s/^http_addr =.*/http_addr = 127.0.0.1/' /etc/grafana/grafana.ini 2>/dev/null || true"
sh_run "sed -i 's/^;domain =.*/domain = $GRAFANA_HOST.$DOMAIN/; s/^domain =.*/domain = $GRAFANA_HOST.$DOMAIN/; s#^;root_url =.*#root_url = https://$GRAFANA_HOST.$DOMAIN#; s#^root_url =.*#root_url = https://$GRAFANA_HOST.$DOMAIN#; s/^;root_url =/#root_url = https:\/\/$GRAFANA_HOST.$DOMAIN/' /etc/grafana/grafana.ini 2>/dev/null || true"

if systemctl list-unit-files 2>/dev/null | grep -q '^grafana-server.service'; then
  sh_run "mkdir -p /etc/systemd/system/grafana-server.service.d"
  sh_run "sed 's|DOMAIN_PLACEHOLDER|$GRAFANA_HOST.$DOMAIN|' '$STAGE/grafana-server.service.override' > '$STAGE/grafana-override.final'"
  sh_run "install -m 644 '$STAGE/grafana-override.final' /etc/systemd/system/grafana-server.service.d/override.conf"
fi

# ================================================================ nginx ======
c_step "Web publishing"
if [ "$WEB_MODE" = "none" ]; then
  c_ok "--web none: skipping nginx entirely"
  c_note "Grafana listens on 127.0.0.1:$GRAFANA_PORT only."
  c_note "Reach it with:  ssh -L $GRAFANA_PORT:127.0.0.1:$GRAFANA_PORT <this-server>"
  c_note "Then open http://127.0.0.1:$GRAFANA_PORT in your browser."
  # No domain, no TLS, no vhost. Grafana must not try to redirect to a host
  # that does not exist.
  sh_run "sed -i 's#^;root_url =.*#root_url = http://127.0.0.1:$GRAFANA_PORT#; s#^root_url =.*#root_url = http://127.0.0.1:$GRAFANA_PORT#; s#^;domain =.*#domain = 127.0.0.1#; s#^domain =.*#domain = 127.0.0.1#' /etc/grafana/grafana.ini 2>/dev/null || true"
  # A "secure" cookie is never returned over plain HTTP, so login would loop.
  sh_run "sed -i 's#^;cookie_secure =.*#cookie_secure = false#; s#^cookie_secure =.*#cookie_secure = false#' /etc/grafana/grafana.ini 2>/dev/null || true"

  c_step "Starting services"
  sh_run "systemctl daemon-reload"
  for u in http-over-ssh prometheus prometheus-node-exporter grafana-server; do
    if systemctl list-unit-files 2>/dev/null | grep -q "^${u}"; then
      sh_run "systemctl enable --now $u"
    else
      c_warn "unit '$u' not present — skipped"
    fi
  done

  # Bundle + summary still needed.
  write_native_bundle
  native_summary "http://127.0.0.1:$GRAFANA_PORT"
  exit 0
fi

NGINX_AVAIL="/etc/nginx/sites-available/$GRAFANA_HOST.conf"
NGINX_EN="/etc/nginx/sites-enabled/$GRAFANA_HOST.conf"
sh_run "mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled"

# Detect an existing certificate. We must NOT invent filenames: a vhost that
# references a missing cert makes `nginx -t` fail and, worse, a reload would
# then leave the operator without a working web server.
CERT=""; CERT_KEY=""
# Rate limiting needs a limit_req_zone declared in nginx.conf's http{} block.
# A stock nginx has none, so we only emit limit_req when one actually exists —
# otherwise nginx -t fails on an unknown zone and the vhost is unusable.
HAVE_GENERAL_ZONE=0
if have nginx && nginx -T 2>/dev/null | grep -q 'limit_req_zone[^;]*zone=general'; then
  HAVE_GENERAL_ZONE=1
fi

find_cert() {
  local f d
  # Let's Encrypt / certbot
  for f in /etc/letsencrypt/live/*/fullchain.pem; do
    [ -f "$f" ] && { d="$(dirname "$f")"; CERT="$f"; CERT_KEY="$d/privkey.pem"; return 0; }
  done
  # A common single-file wildcard layout (pair with an existing vhost style)
  for f in /etc/nginx/certs/wildcard.crt /etc/nginx/ssl/wildcard.crt \
           /etc/ssl/certs/wildcard.crt /etc/nginx/certs/fullchain.pem; do
    [ -f "$f" ] && { CERT="$f"; CERT_KEY="${f%.*}.key"; [ -f "$CERT_KEY" ] && return 0; }
    [ -f "$f" ] && { d="$(dirname "$f")"; CERT="$f"; CERT_KEY="$d/$(basename "${f%.*}").key"
                     [ -f "$CERT_KEY" ] && return 0; }
  done
  return 1
}

if have nginx; then
  if find_cert; then
    c_ok "certificate found: $CERT"
    [ -f "$CERT_KEY" ] || { c_err "found cert but no matching key at $CERT_KEY"; exit 1; }
  else
    c_warn "no TLS certificate found — writing a PORT 80 ONLY vhost."
    c_note "Grafana will be reachable over plain HTTP until you add a certificate."
    c_note "Obtain one, then re-run this script to enable HTTPS."
  fi
else
  c_warn "nginx not installed — skipping the vhost entirely"
  c_note "Grafana will then be reachable only on 127.0.0.1:$GRAFANA_PORT"
  c_note "Use an SSH tunnel to reach it:  ssh -L 3000:127.0.0.1:$GRAFANA_PORT <server>"
  CERT=""; CERT_KEY=""
fi

{
if [ -n "$CERT" ]; then
cat <<EOF
# Grafana behind nginx. Generated by monitoring-server-setup-native.sh
# Grafana listens on 127.0.0.1:$GRAFANA_PORT and is NOT internet-facing.
#
# TLS note: the rate-limit zones below must be defined in the http{} block of
# nginx.conf, or nginx -t will fail. They look like:
#   limit_req_zone \$binary_remote_addr zone=general:10m rate=10r/s;
# If your nginx.conf does not define zone=general, remove the limit_req line.
server {
    listen 443 ssl;
    http2 on;
    server_name $GRAFANA_HOST.$DOMAIN;

    ssl_certificate     $CERT;
    ssl_certificate_key $CERT_KEY;

    add_header X-Frame-Options        "SAMEORIGIN"    always;
    add_header X-Content-Type-Options "nosniff"       always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;

    location = /login {
$( [ "$HAVE_GENERAL_ZONE" -eq 1 ] && echo '        limit_req zone=general burst=10 nodelay;' || echo '        # limit_req omitted: no limit_req_zone named "general" in nginx.conf' )

        proxy_pass http://127.0.0.1:$GRAFANA_PORT;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:$GRAFANA_PORT;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support for Grafana Live.
        proxy_http_version 1.1;
        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}

server {
    listen 80;
    server_name $GRAFANA_HOST.$DOMAIN;
    return 301 https://\$host\$request_uri;
}
EOF
else
cat <<EOF
# Grafana behind nginx. Generated by monitoring-server-setup-native.sh
# Grafana listens on 127.0.0.1:$GRAFANA_PORT and is NOT internet-facing.
#
# NO CERTIFICATE WAS FOUND, so this vhost is plain HTTP only. Add a
# certificate, then re-run the script to switch this to HTTPS with a redirect.
server {
    listen 80;
    server_name $GRAFANA_HOST.$DOMAIN;

    location = /login {
        proxy_pass http://127.0.0.1:$GRAFANA_PORT;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:$GRAFANA_PORT;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
    }
}
EOF
fi
} > "$STAGE/$GRAFANA_HOST.conf"

echo "  --- vhost ---"
sed 's/^/       /' "$STAGE/$GRAFANA_HOST.conf"
confirm
sh_run "install -m 644 '$STAGE/$GRAFANA_HOST.conf' '$NGINX_AVAIL'"
sh_run "ln -sf '$NGINX_AVAIL' '$NGINX_EN'"
if [ "$DRY_RUN" -eq 0 ] && have nginx; then
  # Test before reload, always. A bad vhost must not take the web server down.
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx || systemctl restart nginx
    c_ok "nginx reloaded"
  else
    c_err "nginx config invalid — NOT reloading. Fix or remove:"
    c_note "$NGINX_AVAIL"
    nginx -t 2>&1 | tail -5 | sed 's/^/       /'
  fi
fi

# ================================================================ start ======
c_step "Starting services"
sh_run "systemctl daemon-reload"
for u in http-over-ssh prometheus prometheus-node-exporter grafana-server; do
  if systemctl list-unit-files 2>/dev/null | grep -q "^${u}"; then
    sh_run "systemctl enable --now $u"
  else
    c_warn "unit '$u' not present — skipped"
  fi
done

if [ "$DRY_RUN" -eq 0 ]; then
  sleep 4
  c_step "Status"
  for u in http-over-ssh prometheus prometheus-node-exporter grafana-server; do
    st="$(systemctl is-active "$u" 2>/dev/null || echo 'not found')"
    printf '       %-26s %s\n' "$u" "$st"
  done
  echo
  c_note "ports actually listening:"
  ss -lntp 2>/dev/null | grep -E ":($PROXY_PORT|$PROM_PORT|$GRAFANA_PORT|$EXPORT_PORT)\b" | sed 's/^/       /' || c_note "(none yet)"
fi

c_step "Admin panel (optional)"
# The panel is a separate binary so a Grafana-only install never needs Go.
if have monitoring-admin || systemctl list-unit-files 2>/dev/null | grep -q '^monitoring-admin'; then
  c_ok "monitoring-admin present"
  sh_run "systemctl enable --now monitoring-admin"
  c_note "installer served at http://127.0.0.1:${ADMIN_PORT}/install.sh"
  c_note "create a client in the panel to get the one-line install command"
else
  c_note "panel not installed. To add it:"
  c_note "  git clone https://github.com/marufmoinuddin/monitoring-stack-setup.git"
  c_note "  cd monitoring-stack-setup && make install"
  c_note "  sudo install -m 644 monitoring-admin.service /etc/systemd/system/"
  c_note "  sudo systemctl enable --now monitoring-admin"
fi

# =============================================================== bundle ======
# Shared by the --web none early exit and the normal path, so both produce an
# identical bundle file.
# =============================================================== bundle ======
c_step "Client bundle"
VPS_IP="$(ip -4 -br addr show scope global 2>/dev/null | awk '{print $3}' | cut -d/ -f1 | head -1)"
[ -z "$VPS_IP" ] && VPS_IP="<set-your-server-ip>"
HOST_FPR="$(ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub 2>/dev/null | awk '{print $2}')"
PROXY_PUB=""
[ -f "$CONF_DIR/id_ed25519.pub" ] && PROXY_PUB="$(cat "$CONF_DIR/id_ed25519.pub")"
GF_PW=""
[ -f "$STATE_DIR/grafana-admin-password" ] && GF_PW="$(cat "$STATE_DIR/grafana-admin-password")"

if [ "$DRY_RUN" -eq 0 ]; then
  umask 077
  cat > "$BUNDLE" <<EOF
# Generated by monitoring-server-setup-native.sh. Mode 600 — contains a password.
#   scp <server>:$BUNDLE <client>:
#   ./monitoring-client-setup.sh --bundle client-bundle.env
VPS_HOST=$VPS_IP
VPS_HOST_KEY_FINGERPRINT=$HOST_FPR
TUNNEL_PORT=${TUNNEL_PORTS[0]}
PROXY_PUBKEY=$PROXY_PUB
GRAFANA_URL=https://$GRAFANA_HOST.$DOMAIN
GRAFANA_USER=admin
GRAFANA_PASSWORD=$GF_PW
EOF
  chmod 600 "$BUNDLE"
  c_ok "written: $BUNDLE"
else
  c_note "[dry-run] would write $BUNDLE"
fi

cat <<EOF

$(printf '\033[1;32m')=========================================================
 Native server setup complete — no Docker involved.
=========================================================$(printf '\033[0m')

 Next, on each client machine:

   scp $BUNDLE ./monitoring-client-setup.sh <client>:
   ssh <client>
   chmod +x monitoring-client-setup.sh
   ./monitoring-client-setup.sh --bundle client-bundle.env --dry-run
   ./monitoring-client-setup.sh --bundle client-bundle.env --name my-laptop

 Then back here:

   ./monitoring-server-setup-native.sh --add-client-key "ssh-ed25519 AAAA... my-laptop"

 Grafana: https://$GRAFANA_HOST.$DOMAIN
   admin / password in $STATE_DIR/grafana-admin-password

 Verify:
   systemctl status http-over-ssh prometheus grafana-server
   curl -sI http://127.0.0.1:$PROM_PORT/-/healthy
   curl -s http://127.0.0.1:$PROM_PORT/api/v1/query?query=up

EOF